runtime: custom
env: flex

service: frontend

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: .5
  disk_size_gb: .5

env_variables:
  # Add any required environment variables here
  # For example, REACT_APP_API_URL: "https://api.example.com"
